server:
  port: 8080


spring:
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


  redis:
    host: 127.0.0.1
    port: 6379
    password:

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/photography?serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Mj1314521
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: bosPoolName
      max-lifetime: 1800000
      idle-timeout: 30000
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5


# mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.cc.pic.api.pojo
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段验证策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    # 驼峰下划线转换
    #db-column-underline: true
    # 数据库大写下划线转换
    #capital-mode: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 逻辑已删除值(默认为 1)
    logic-delete-value: 1
    # 逻辑未删除值(默认为 0)
    logic-not-delete-value: 0
  configuration:
    #map-underscore-to-camel-case: true
    cache-enabled: true
